#!/bin/bash

echo "========================================="
echo "실제 데이터베이스 구독 정보 확인"
echo "========================================="

# D1 데이터베이스 쿼리 (Wrangler CLI 사용)
echo ""
echo "1. 활성 구독 목록 조회"
npx wrangler d1 execute superplace-db --command="SELECT id, userId, planName, status, startDate, endDate, max_students, current_students FROM user_subscriptions WHERE status = 'active' LIMIT 5" 2>/dev/null || echo "Wrangler 명령 실행 실패"

echo ""
echo "2. 학원장 계정 조회"
npx wrangler d1 execute superplace-db --command="SELECT id, email, role, academyId FROM User WHERE role = 'DIRECTOR' LIMIT 5" 2>/dev/null || echo "Wrangler 명령 실행 실패"

echo ""
echo "========================================="
echo "프론트엔드 디버깅 가이드"
echo "========================================="
echo ""
echo "학원장 설정 페이지 로딩 문제 해결 방법:"
echo ""
echo "1. 브라우저 개발자 도구 확인:"
echo "   - F12를 눌러 개발자 도구 열기"
echo "   - Console 탭에서 오류 메시지 확인"
echo "   - Network 탭에서 API 호출 확인"
echo ""
echo "2. API 응답 확인:"
echo "   - /api/subscription/check?academyId=xxx 호출 확인"
echo "   - 응답 상태 코드 확인 (200, 404, 500 등)"
echo "   - 응답 JSON 구조 확인"
echo ""
echo "3. localStorage 확인:"
echo "   - Application 탭 > Local Storage"
echo "   - 'user' 키의 값 확인"
echo "   - academyId 필드 존재 여부 확인"
echo ""
echo "4. 일반적인 문제:"
echo "   - academyId가 null이거나 undefined"
echo "   - API가 404 또는 500 오류 반환"
echo "   - CORS 정책으로 인한 차단"
echo "   - 잘못된 API 엔드포인트 경로"
echo ""
