#!/bin/bash
echo "🚀 배포 확인 중..."
echo ""
echo "커밋 ID: $(git rev-parse --short HEAD)"
echo "커밋 메시지: $(git log -1 --pretty=%B | head -1)"
echo ""
echo "⏳ Cloudflare Pages 배포 대기 중..."
echo "   예상 배포 시간: 3-5분"
echo ""
echo "📋 배포 후 확인 사항:"
echo "   1. https://suplacestudy.com/dashboard/admin/ai-bots/assign/ 접속"
echo "   2. F12 개발자 도구 열기"
echo "   3. Console 탭에서 다음 로그 확인:"
echo "      - 📤 학원 할당 요청: (payload)"
echo "      - 📥 Received request body: (서버 로그)"
echo "      - 🔍 Parsed fields: (파싱된 필드)"
echo "   4. 할당 실행 시 400 에러 발생 시:"
echo "      - 에러 응답에 'received' 필드 확인"
echo "      - 어떤 필드가 누락/잘못되었는지 정확히 표시됨"
echo ""
echo "🔍 디버깅 정보:"
echo "   - botId 전송 여부 확인"
echo "   - studentCount 타입 확인 (숫자 vs 문자열)"
echo "   - 날짜 형식 확인 (YYYY-MM-DD)"
