#!/bin/bash

echo "=== Solapi 카카오 플러스친구 API 파라미터 확인 ==="
echo ""
echo "🔍 현재 전송 중인 파라미터:"
echo "{"
echo "  \"searchId\": \"꾸메땅학원\","
echo "  \"phoneNumber\": \"01085328739\","
echo "  \"categoryCode\": \"CS02\","
echo "  \"token\": \"123456\""
echo "}"
echo ""

echo "❌ 에러: '카테고리를 선택해주세요'"
echo ""

echo "💡 가능한 원인:"
echo "1. 필드명이 'categoryCode'가 아님"
echo "   → 'category', 'categoryId', 'categoryType' 등일 수 있음"
echo ""
echo "2. 카테고리 코드 형식이 잘못됨"
echo "   → 'CS02' 대신 다른 형식 필요"
echo ""
echo "3. searchId에 @ 필요"
echo "   → '@꾸메땅학원' 형식"
echo ""
echo "4. categoryCode가 선택사항이 아니라 필수이지만 다른 값 필요"
echo ""

echo "🧪 테스트 방법:"
echo "1. categoryCode 필드명 변경 테스트"
echo "   - categoryCode → category"
echo "   - categoryCode → categoryId"
echo "   - categoryCode → subjectCategory"
echo ""
echo "2. searchId에 @ 추가 테스트"
echo "   - '꾸메땅학원' → '@꾸메땅학원'"
echo ""
echo "3. 카테고리 코드 형식 변경 테스트"
echo "   - 'CS02' → '교육'"
echo "   - 'CS02' → '002001'"
echo "   - 'CS02' → 숫자로 변환"
echo ""

echo "📋 다음 단계:"
echo "1. searchId에 @ 추가해서 테스트 (가장 의심됨)"
echo "2. categoryCode 제거하고 테스트"
echo "3. Solapi 공식 문서 재확인"
