// FK 제약 조건 확인 스크립트
const testProductId = 'bot-1772458232285-1zgtygvh1';
const testAcademyId = 'academy_1735456320741_yykkfv8bw';

console.log('🔍 외래 키 제약 조건 확인');
console.log('='.repeat(50));
console.log(`테스트 productId: ${testProductId}`);
console.log(`테스트 academyId: ${testAcademyId}`);
console.log('='.repeat(50));
console.log('\n✅ Cloudflare D1 콘솔에서 다음 쿼리 실행:\n');
console.log('1️⃣ AcademyBotSubscription 테이블 외래 키 확인:');
console.log('PRAGMA foreign_key_list(AcademyBotSubscription);');
console.log('');
console.log('2️⃣ Academy 테이블에 academyId가 존재하는지 확인:');
console.log(`SELECT id, name FROM Academy WHERE id = '${testAcademyId}';`);
console.log('');
console.log('3️⃣ 참조될 수 있는 Product 또는 StoreProduct 테이블 확인:');
console.log(`SELECT id, name, productName FROM StoreProduct WHERE id = '${testProductId}';`);
console.log('-- 또는');
console.log(`SELECT * FROM sqlite_master WHERE type='table' AND name LIKE '%Product%';`);
console.log('');
console.log('4️⃣ 모든 학원 목록 조회:');
console.log('SELECT id, name, createdAt FROM Academy LIMIT 10;');
console.log('');
console.log('5️⃣ 외래 키 제약 강제 적용 상태 확인:');
console.log('PRAGMA foreign_keys;');
console.log('');
console.log('💡 예상되는 문제:');
console.log('- productId가 참조하는 테이블(예: StoreProduct)에 해당 ID가 없음');
console.log('- academyId가 Academy 테이블에 존재하지 않음');
console.log('- 외래 키 제약이 활성화되어 있지만 참조 무결성이 깨짐');
console.log('');
console.log('🔧 해결 방법:');
console.log('옵션 1) 외래 키 제약을 임시로 비활성화:');
console.log('   PRAGMA foreign_keys = OFF;');
console.log('   (권장하지 않음)');
console.log('');
console.log('옵션 2) AcademyBotSubscription 테이블에서 FK 제거 (재생성):');
console.log('   -- 백업');
console.log('   CREATE TABLE AcademyBotSubscription_backup AS SELECT * FROM AcademyBotSubscription;');
console.log('   -- 제거');
console.log('   DROP TABLE AcademyBotSubscription;');
console.log('   -- FK 없이 재생성');
console.log('   CREATE TABLE AcademyBotSubscription (');
console.log('     id TEXT PRIMARY KEY,');
console.log('     academyId TEXT NOT NULL,  -- FK 제약 제거');
console.log('     productId TEXT NOT NULL,  -- FK 제약 제거');
console.log('     productName TEXT,');
console.log('     totalStudentSlots INTEGER DEFAULT 0,');
console.log('     usedStudentSlots INTEGER DEFAULT 0,');
console.log('     remainingStudentSlots INTEGER DEFAULT 0,');
console.log('     subscriptionStart TEXT NOT NULL,');
console.log('     subscriptionEnd TEXT NOT NULL,');
console.log('     createdAt TEXT DEFAULT CURRENT_TIMESTAMP,');
console.log('     updatedAt TEXT DEFAULT CURRENT_TIMESTAMP');
console.log('   );');
console.log('   -- 복원');
console.log('   INSERT INTO AcademyBotSubscription SELECT * FROM AcademyBotSubscription_backup;');
console.log('   -- 백업 삭제');
console.log('   DROP TABLE AcademyBotSubscription_backup;');
console.log('');
console.log('옵션 3) 승인 시 참조 데이터가 존재하는지 확인하는 로직 추가 (권장):');
console.log('   - approve.ts에서 Academy와 Product 존재 여부 확인');
console.log('   - 존재하지 않으면 오류 메시지 반환');
