#!/bin/bash

echo "📊 Cloudflare Pages 로그 확인 방법"
echo "======================================"
echo ""
echo "1️⃣ Cloudflare Dashboard로 이동:"
echo "   https://dash.cloudflare.com/"
echo ""
echo "2️⃣ Pages 프로젝트 선택:"
echo "   superplace 또는 superplacestudy"
echo ""
echo "3️⃣ Real-time Logs 확인:"
echo "   - 상단 메뉴에서 'Logs' 클릭"
echo "   - 'Real-time Logs' 탭 선택"
echo "   - 'Begin log stream' 클릭"
echo ""
echo "4️⃣ 학생/학원장 계정에서 AI 챗봇 사용 후 로그 확인"
echo ""
echo "======================================"
echo ""
echo "🧪 또는 로컬에서 wrangler로 로그 확인:"
echo "-----------------------------------"
echo ""
echo "# Pages Functions 로그 스트리밍"
echo "npx wrangler pages deployment tail --project-name=superplacestudy"
echo ""
echo "======================================"
echo ""
echo "💡 학생/학원장 계정 정보:"
echo "-----------------------------------"
echo "웹사이트: https://suplacestudy.com"
echo ""
echo "학원장 계정:"
echo "  - 이메일: 학원장 이메일 주소"
echo "  - 역할: director"
echo ""
echo "학생 계정:"
echo "  - 이메일: 학생 이메일 주소"
echo "  - 역할: student"
echo ""
echo "======================================"
echo ""
echo "🔍 현재 배포 상태:"
echo "-----------------------------------"
echo "최근 Commit: $(git log --oneline -1)"
echo "배포 URL: https://suplacestudy.com"
echo "API 엔드포인트: /api/ai-chat"
echo ""
echo "======================================"

