#!/bin/bash

echo "🚀 Vectorize 인덱스 생성 가이드"
echo "================================"
echo ""
echo "⚠️  주의: CLI 인증이 필요합니다!"
echo ""
echo "📌 방법 1: Cloudflare Dashboard (가장 쉬움) ⭐"
echo "-------------------------------------------"
echo "1. 브라우저에서 열기:"
echo "   👉 https://dash.cloudflare.com/"
echo ""
echo "2. 좌측 메뉴에서 'Workers & Pages' 클릭"
echo ""
echo "3. 'Vectorize' 탭 클릭"
echo ""
echo "4. 'Create Index' 버튼 클릭"
echo ""
echo "5. 다음 정보 입력:"
echo "   - Index Name: knowledge-base-embeddings"
echo "   - Dimensions: 768"
echo "   - Metric: cosine"
echo ""
echo "6. 'Create' 버튼 클릭"
echo ""
echo "7. Status가 'Active'가 되면 완료!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 방법 2: API 토큰 사용 (고급)"
echo "-------------------------------------------"
echo "1. API 토큰 생성:"
echo "   👉 https://dash.cloudflare.com/profile/api-tokens"
echo ""
echo "2. 'Create Token' 클릭"
echo ""
echo "3. Template: 'Edit Cloudflare Workers' 선택"
echo ""
echo "4. Permissions 추가:"
echo "   - Account / Vectorize / Edit"
echo ""
echo "5. 'Continue' → 'Create Token'"
echo ""
echo "6. 토큰 복사 (한 번만 표시됨!)"
echo ""
echo "7. 터미널에서 실행:"
echo "   export CLOUDFLARE_API_TOKEN='your-token-here'"
echo "   cd /home/user/webapp"
echo "   npx wrangler@latest vectorize create knowledge-base-embeddings \\"
echo "     --dimensions=768 \\"
echo "     --metric=cosine"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 인덱스 생성 후 다음 단계:"
echo "-------------------------------------------"
echo "1. wrangler.toml 파일 수정 (23-25줄 주석 제거):"
echo "   [[vectorize]]"
echo "   binding = \"VECTORIZE\""
echo "   index_name = \"knowledge-base-embeddings\""
echo ""
echo "2. 배포:"
echo "   cd /home/user/webapp"
echo "   git add wrangler.toml"
echo "   git commit -m 'feat(vectorize): Vectorize 바인딩 활성화'"
echo "   git push origin main"
echo ""
echo "3. 배포 완료 대기 (3-5분)"
echo ""
echo "4. 테스트:"
echo "   - PDF 업로드: https://superplacestudy.pages.dev/dashboard/admin/ai-bots/create"
echo "   - AI 챗: https://superplacestudy.pages.dev/ai-chat"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📞 도움이 필요하신가요?"
echo "-------------------------------------------"
echo "상세 가이드: /home/user/webapp/RAG_ACTIVATION_GUIDE.md"
echo "GitHub: https://github.com/kohsunwoo12345-cmyk/superplace"
echo ""
echo "🎉 Dashboard 방법(방법 1)을 추천합니다!"
