#!/bin/bash

# Vercel 배포 스크립트

echo "🚀 SUPER PLACE Vercel 배포 가이드"
echo "=================================="
echo ""
echo "📋 배포 전 체크리스트:"
echo ""
echo "✅ 1. Vercel 계정 생성 (https://vercel.com)"
echo "✅ 2. GitHub 저장소 연결됨: https://github.com/kohsunwoo12345-cmyk/superplace"
echo "✅ 3. PostgreSQL 데이터베이스 준비 (Neon 또는 Supabase)"
echo ""
echo "📝 필수 환경 변수 (Vercel 대시보드에서 설정):"
echo ""
echo "DATABASE_URL=postgresql://user:password@host:5432/database"
echo "NEXTAUTH_URL=https://superplace.vercel.app"
echo "NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo "GOOGLE_GENERATIVE_AI_API_KEY=AIzaSy..."
echo "GOOGLE_GEMINI_API_KEY=AIzaSy..."
echo ""
echo "🔗 배포 단계:"
echo ""
echo "1. Vercel 대시보드 (https://vercel.com/dashboard) 접속"
echo "2. 'Add New...' → 'Project' 클릭"
echo "3. 'Import Git Repository' 선택"
echo "4. 'kohsunwoo12345-cmyk/superplace' 검색 및 선택"
echo "5. 'Import' 클릭"
echo "6. 'Environment Variables' 섹션에서 위의 5개 환경 변수 추가"
echo "7. 'Deploy' 버튼 클릭"
echo "8. 배포 완료 대기 (약 2-3분)"
echo ""
echo "📊 배포 후:"
echo ""
echo "1. 배포 URL 확인"
echo "2. 회원가입 테스트 (학원장)"
echo "3. 학원 생성 확인"
echo "4. 초대 코드 확인"
echo ""
echo "🆘 문제 발생 시:"
echo ""
echo "- DEPLOYMENT_GUIDE.md 참고"
echo "- Vercel 로그 확인: Deployments → Logs"
echo "- 환경 변수 확인: Settings → Environment Variables"
echo ""
echo "✨ 배포 준비 완료!"
