#!/bin/bash

echo "🚀 프리뷰 배포를 프로덕션으로 승격합니다..."
echo ""
echo "Cloudflare Dashboard에서 수동으로 승격하는 방법:"
echo ""
echo "1. https://dash.cloudflare.com/ 접속"
echo "2. Workers & Pages → superplacestudy 선택"
echo "3. Deployments 탭 클릭"
echo "4. 프리뷰 배포 찾기:"
echo "   URL: https://791810fd.superplacestudy.pages.dev/"
echo "   또는 Commit: b421cdb"
echo ""
echo "5. 해당 배포의 오른쪽에 있는 ⋮ (세로 점 3개) 클릭"
echo "6. 'Promote to Production' 선택"
echo "7. 확인 후 'Promote' 버튼 클릭"
echo ""
echo "✅ 승격 완료 후 1-2분 대기"
echo "✅ 테스트: https://superplacestudy.pages.dev/login"
echo ""
echo "또는 suplacestudy.pages.dev 프로젝트에서도 동일하게 진행"
