#!/bin/bash
echo "🚀 배포 대기 중..."
echo "⏰ 3분 대기 후 확인..."
sleep 180

echo ""
echo "✅ 배포 완료! 이제 테스트하세요."
echo ""
echo "📋 수정 사항:"
echo "1. ✅ HMAC 서명 생성 방식을 send-bulk.ts와 동일하게 수정"
echo "   - date + salt 방식으로 변경"
echo "   - 서명 생성 로그 추가"
echo ""
echo "2. ✅ Solapi API 키 로드 로직 개선"
echo "   - 여러 환경 변수명 시도 (SOLAPI_API_Key, SOLAPI_API_KEY 등)"
echo "   - .trim() 처리 추가"
echo "   - 상세한 로그 추가"
echo ""
echo "3. ✅ 상세 로그 추가"
echo "   - 🔑 Solapi 자격 증명 상태"
echo "   - 🔐 인증 헤더 정보 (preview)"
echo "   - 🚀 Solapi API 호출 데이터"
echo ""
echo "📍 테스트 페이지:"
echo "   https://superplacestudy.pages.dev/dashboard/kakao-alimtalk/templates/create/"
echo ""
echo "🧪 테스트 방법:"
echo "1. 페이지 새로고침 (Ctrl+F5)"
echo "2. 카카오 채널 선택"
echo "3. 템플릿 정보 입력:"
echo "   - 템플릿 코드: TEST_001"
echo "   - 템플릿 이름: 테스트 템플릿"
echo "   - 내용: 안녕하세요 #{학생이름}님"
echo "   - 카테고리: 선택"
echo "4. 등록 버튼 클릭"
echo "5. F12 콘솔에서 로그 확인:"
echo "   - 🔑 Solapi 자격 증명: { keyExists: true, secretExists: true }"
echo "   - 🔐 인증 헤더: { date, salt, signaturePreview }"
echo "   - 🚀 Solapi API 호출: { pfId, templateId, name, content, ... }"
echo "   - 📥 Solapi 응답: { status: 200/201, ok: true, data }"
echo ""
echo "⚠️ 예상 결과:"
echo "   ✅ 성공: '템플릿이 등록되었습니다!' 알림"
echo "   ❌ 실패: 콘솔에서 Solapi 응답 상세 확인"
echo ""
echo "💡 문제가 계속되면:"
echo "   - F12 콘솔의 전체 로그 복사해서 제공"
echo "   - Network 탭에서 /api/kakao/templates/register 응답 확인"
echo ""
