#!/bin/bash
echo "=== 🤖 AI 시스템 페이지 테스트 ==="
echo ""
echo "⏳ 배포 대기 중 (30초)..."
sleep 30
echo ""
echo "✅ 배포 완료 추정 시각: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""

echo "📋 최근 커밋:"
git log -1 --pretty=format:"   커밋: %h%n   메시지: %s%n   시각: %ai"
echo ""
echo ""

echo "🔍 테스트 시나리오:"
echo ""
echo "1️⃣ 학원장 로그인"
echo "   - https://superplacestudy.pages.dev/login"
echo "   - 학원장 계정으로 로그인"
echo ""

echo "2️⃣ AI 시스템 접속"
echo "   - 좌측 메뉴에서 'AI 시스템' 클릭"
echo "   - 또는 직접 접속: https://superplacestudy.pages.dev/dashboard/director/ai-system"
echo ""

echo "3️⃣ 브라우저 콘솔 확인 (F12)"
echo "   - 다음 로그가 출력되는지 확인:"
echo "     📋 Loading data for academy {ID}"
echo "     🤖 Fetching bots for academy {ID}..."
echo "     ✅ Loaded {N} bots: [...]"
echo "     👨‍🎓 Fetching students for academy {ID}..."
echo "     ✅ Loaded {N} students: [...]"
echo "     👨‍🏫 Fetching teachers for academy {ID}..."
echo "     ✅ Loaded {N} teachers: [...]"
echo ""

echo "4️⃣ 봇 할당 탭에서 확인"
echo "   - 'AI 봇 선택' 드롭다운에 봇 목록이 표시되는지"
echo "   - '학생 선택' 드롭다운에 학생 목록이 표시되는지"
echo "   - 각 드롭다운 옆에 개수가 표시되는지 (예: '(5명)')"
echo ""

echo "5️⃣ 비어있는 경우 확인"
echo "   - 봇이 없으면: '사용 가능한 봇이 없습니다' 메시지"
echo "   - 학생이 없으면: '등록된 학생이 없습니다' 메시지"
echo ""

echo "💡 문제 해결:"
echo "   - 학생 목록이 비어있으면:"
echo "     1. localStorage에서 user 정보 확인 (F12 → Console)"
echo "        localStorage.getItem('user')"
echo "     2. academyId 또는 academy_id 필드가 있는지 확인"
echo "     3. 콘솔에서 API 호출 에러 메시지 확인"
echo ""
echo "   - API 직접 테스트 (콘솔에서 실행):"
echo "     const user = JSON.parse(localStorage.getItem('user'));"
echo "     const academyId = user.academy_id || user.academyId;"
echo "     fetch(\`/api/director/users?role=STUDENT&academyId=\${academyId}\`)"
echo "       .then(r => r.json()).then(console.log);"
