#!/bin/bash
echo "=== 📊 학원장 대시보드 테스트 ==="
echo ""
echo "⏳ 배포 대기 중 (30초)..."
sleep 30
echo ""
echo "✅ 배포 완료 추정 시각: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""

echo "📋 최근 커밋:"
git log -1 --pretty=format:"   커밋: %h%n   메시지: %s%n   시각: %ai"
echo ""
echo ""

echo "🔍 테스트 시나리오:"
echo ""
echo "1️⃣ 학원장 로그인"
echo "   - https://superplacestudy.pages.dev/login"
echo "   - 학원장 계정으로 로그인"
echo ""

echo "2️⃣ 대시보드 접속"
echo "   - 로그인 후 자동으로 대시보드로 이동"
echo "   - 또는 직접: https://superplacestudy.pages.dev/dashboard"
echo ""

echo "3️⃣ 확인할 데이터 (4개 카드)"
echo "   ✅ 전체 학생: XX명 (선생님 X명)"
echo "   ✅ 오늘 출석: XX명 (출석률 XX%)"
echo "   ✅ 숙제 제출: XX개 (오늘 제출됨)"
echo "   ✅ 미제출: XX명 (숙제 미제출)"
echo ""

echo "4️⃣ 확인할 목록 (3개 카드)"
echo "   ✅ 오늘 출석 알림: 최근 5명 (숙제 제출 여부)"
echo "   ✅ 숙제 검사 결과: 점수, 과목, 완성도, 노력도"
echo "   ✅ 숙제 미제출: 출석 시각 포함"
echo ""

echo "5️⃣ 브라우저 콘솔 확인 (F12)"
echo "   - 다음 로그 확인:"
echo "     📊 Director stats - academyId: XX"
echo "     ✅ Total students: XX"
echo "     ✅ Today attendance: XX"
echo "     ✅ Today homework submitted: XX"
echo "     ✅ Today missing homework: XX"
echo "     ✅ Attendance alerts: X"
echo "     ✅ Homework results: X"
echo "     ✅ Missing homework list: X"
echo "     📊 Final stats: {...}"
echo ""

echo "💡 문제 해결:"
echo "   - 데이터가 0으로 표시되면:"
echo "     1. localStorage의 user 정보 확인"
echo "        localStorage.getItem('user')"
echo "     2. academyId 확인 (academy_id 또는 academyId)"
echo "     3. 브라우저 콘솔에서 API 직접 호출:"
echo "        const user = JSON.parse(localStorage.getItem('user'));"
echo "        const academyId = user.academy_id || user.academyId;"
echo "        fetch(\`/api/dashboard/director-stats?academyId=\${academyId}&role=DIRECTOR&userId=\${user.id}\`)"
echo "          .then(r => r.json()).then(console.log);"
echo ""

echo "   - 테이블이 없다는 에러가 나면:"
echo "     1. attendance 테이블 확인 (D1 콘솔)"
echo "     2. homework_submissions 테이블 확인"
echo "     3. 테이블 구조가 API와 일치하는지 확인"
