#!/bin/bash

# 학생 삭제 기능 테스트 스크립트
# Test script for student deletion feature

API_BASE="https://superplacestudy.pages.dev"

echo "========================================="
echo "학생 삭제 기능 테스트"
echo "========================================="
echo ""

echo "📋 구현된 기능:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣ 학원 상세페이지 등록일 표시"
echo "   • 회원가입일(User.createdAt)로 표시"
echo "   • API: GET /api/admin/academies?id=xxx"
echo "   • 응답: students[].createdAt 필드"
echo ""

echo "2️⃣ 학생 완전 삭제 API"
echo "   • API: DELETE /api/admin/students/[id]"
echo "   • 삭제되는 데이터:"
echo "     ├─ User 테이블 (학생 계정)"
echo "     ├─ students 테이블"
echo "     ├─ class_students 테이블 (클래스 배정)"
echo "     └─ user_bot_assignments 테이블 (AI 봇 할당)"
echo ""
echo "   • 자동 처리:"
echo "     └─ 구독의 current_students 카운트 -1"
echo ""

echo "3️⃣ 삭제 효과"
echo "   • ❌ 로그인 불가 (User 테이블에서 제거)"
echo "   • ❌ AI 봇 할당 불가 (user_bot_assignments 삭제)"
echo "   • ❌ 학생 수 카운트에서 제외 (User 테이블 role='STUDENT' 조회)"
echo "   • ❌ 클래스 배정에서 제외 (class_students 삭제)"
echo ""

echo "========================================="
echo "🧪 테스트 시나리오"
echo "========================================="
echo ""

echo "시나리오 1: 학원 상세 페이지에서 학생 삭제"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 관리자 페이지 접속"
echo "   → https://superplacestudy.pages.dev/dashboard/admin/academies"
echo ""
echo "2. 학원 클릭하여 상세 페이지 이동"
echo "   → 학원 상세 페이지 표시"
echo ""
echo "3. '학생' 탭 클릭"
echo "   → 학생 목록 표시"
echo "   → 각 학생의 등록일(회원가입일) 표시"
echo ""
echo "4. 학생의 '삭제' 버튼 클릭"
echo "   → 확인 다이얼로그 표시:"
echo "     '정말로 XXX 학생을 삭제하시겠습니까?"
echo "     이 작업은 되돌릴 수 없으며, 다음 항목이 모두 삭제됩니다:"
echo "     - 학생 계정"
echo "     - AI 봇 할당"
echo "     - 클래스 배정"
echo "     - 로그인 권한'"
echo ""
echo "5. '확인' 클릭"
echo "   → API 호출: DELETE /api/admin/students/[id]"
echo "   → 성공 메시지: '✅ 학생 XXX이(가) 완전히 삭제되었습니다.'"
echo "   → 페이지 자동 새로고침"
echo "   → 삭제된 학생이 목록에서 사라짐"
echo ""

echo "시나리오 2: 삭제 후 확인 사항"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. 학생 수 카운트 감소 확인"
echo "   → 학원 상세 페이지 상단 '총 학생 수' 카드"
echo "   → 1명 감소 확인"
echo ""
echo "2. 구독 정보의 학생 수 감소 확인"
echo "   → '개요' 탭의 '구독 정보' 카드"
echo "   → '학생 제한' 진행바에서 1명 감소 확인"
echo "   → 예: 30/30 → 29/30"
echo ""
echo "3. 삭제된 학생 로그인 시도"
echo "   → 로그인 페이지에서 삭제된 학생 계정으로 로그인"
echo "   → 실패: '사용자를 찾을 수 없습니다' 또는 유사 오류"
echo ""
echo "4. AI 봇 할당 목록 확인"
echo "   → 관리자 > AI 봇 할당 페이지"
echo "   → 삭제된 학생의 봇 할당 기록 없음"
echo ""

echo "========================================="
echo "📊 DB 변경 사항"
echo "========================================="
echo ""

echo "삭제 전:"
echo "  User 테이블:"
echo "    - id: 123, name: '학생A', role: 'STUDENT', academyId: 'academy-1'"
echo ""
echo "  students 테이블:"
echo "    - user_id: 123, academy_id: 'academy-1'"
echo ""
echo "  class_students 테이블:"
echo "    - studentId: 123, classId: 1"
echo ""
echo "  user_bot_assignments 테이블:"
echo "    - userId: 123, botId: 'bot-1', isActive: 1"
echo ""
echo "  user_subscriptions 테이블 (학원장):"
echo "    - userId: 'director-1', current_students: 30, max_students: 30"
echo ""

echo "삭제 후:"
echo "  User 테이블:"
echo "    - (레코드 삭제됨)"
echo ""
echo "  students 테이블:"
echo "    - (레코드 삭제됨)"
echo ""
echo "  class_students 테이블:"
echo "    - (레코드 삭제됨)"
echo ""
echo "  user_bot_assignments 테이블:"
echo "    - (레코드 삭제됨)"
echo ""
echo "  user_subscriptions 테이블 (학원장):"
echo "    - userId: 'director-1', current_students: 29, max_students: 30"
echo ""

echo "========================================="
echo "🔒 안전장치"
echo "========================================="
echo ""

echo "1. 학생 role 확인"
echo "   → role='STUDENT'인 경우만 삭제 가능"
echo "   → 학원장, 교사 등은 이 API로 삭제 불가"
echo ""

echo "2. 확인 다이얼로그"
echo "   → 삭제 전 사용자에게 경고 메시지 표시"
echo "   → 되돌릴 수 없음을 명시"
echo ""

echo "3. 트랜잭션 처리"
echo "   → 모든 테이블 삭제가 순차적으로 진행"
echo "   → 오류 발생 시 로그 출력 및 계속 진행"
echo ""

echo "========================================="
echo "📝 API 명세"
echo "========================================="
echo ""

echo "DELETE /api/admin/students/[id]"
echo ""
echo "Request:"
echo "  Headers:"
echo "    Authorization: Bearer {token}"
echo ""
echo "  Parameters:"
echo "    id: 학생 ID (User.id)"
echo ""
echo "Response (Success):"
echo '  {
    "success": true,
    "message": "학생 XXX이(가) 완전히 삭제되었습니다.",
    "deletedStudent": {
      "id": "123",
      "name": "학생A",
      "email": "student@example.com"
    }
  }'
echo ""
echo "Response (Error - Not Found):"
echo '  {
    "success": false,
    "error": "학생을 찾을 수 없거나 학생 계정이 아닙니다."
  }'
echo ""
echo "Response (Error - Server):"
echo '  {
    "success": false,
    "error": "Failed to delete student",
    "message": "..."
  }'
echo ""

echo "========================================="
echo "✅ 완료 체크리스트"
echo "========================================="
echo ""

echo "[✅] 학원 상세페이지 등록일 표시 (회원가입일)"
echo "[✅] 학생 삭제 API 구현"
echo "[✅] User 테이블에서 삭제"
echo "[✅] students 테이블에서 삭제"
echo "[✅] class_students 테이블에서 삭제"
echo "[✅] user_bot_assignments 테이블에서 삭제"
echo "[✅] 구독 current_students 감소"
echo "[✅] 학원 상세페이지 삭제 버튼 추가"
echo "[✅] 삭제 확인 다이얼로그"
echo "[✅] 삭제 후 자동 새로고침"
echo ""

echo "========================================="
echo "🚀 배포 정보"
echo "========================================="
echo ""
echo "URL: https://superplacestudy.pages.dev"
echo "Commit: 23bd9e2"
echo "배포 완료: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "변경된 파일:"
echo "  • functions/api/admin/students/[id].ts (새 파일)"
echo "  • src/app/dashboard/admin/academies/detail/page.tsx"
echo ""

echo "========================================="
echo "📚 관련 문서"
echo "========================================="
echo ""
echo "• SUBSCRIPTION_APPROVAL_COMPLETE.md - 요금제 시스템 문서"
echo "• QUICK_REFERENCE.md - 빠른 참조 가이드"
echo ""

echo "========================================="
echo "✅ 테스트 준비 완료!"
echo "========================================="
echo ""
echo "다음 단계:"
echo "1. https://superplacestudy.pages.dev/dashboard/admin/academies 접속"
echo "2. 테스트 학원 선택"
echo "3. '학생' 탭에서 학생 삭제 테스트"
echo "4. 삭제 후 학생 수 감소 확인"
echo "5. 삭제된 학생 로그인 불가 확인"
echo ""
