#!/bin/bash
# Landing Page Template - Real Creation Test
# This script provides step-by-step instructions to manually test landing page creation

echo "=================================================="
echo "🧪 Landing Page Template - Manual Test Guide"
echo "=================================================="
echo ""
echo "이 가이드는 랜딩페이지 템플릿이 실제로 적용되는지"
echo "브라우저에서 수동으로 테스트하는 방법을 안내합니다."
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "=================================================="
echo "📋 Step 1: 로그인"
echo "=================================================="
echo ""
echo -e "${BLUE}URL:${NC} https://superplacestudy.pages.dev/login"
echo ""
echo "✅ 학원장 계정으로 로그인하세요."
echo ""
read -p "로그인이 완료되었으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 2: 랜딩페이지 생성 페이지 접속"
echo "=================================================="
echo ""
echo -e "${BLUE}URL:${NC} https://superplacestudy.pages.dev/dashboard/admin/landing-pages/create"
echo ""
echo "✅ 위 URL로 이동하세요."
echo ""
read -p "페이지가 로드되었으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 3: 개발자 도구 열기"
echo "=================================================="
echo ""
echo "✅ F12 키를 눌러 개발자 도구를 여세요."
echo "✅ Console 탭을 선택하세요."
echo ""
read -p "개발자 도구가 열렸으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 4: 템플릿 선택"
echo "=================================================="
echo ""
echo "✅ '템플릿 선택' 드롭다운을 클릭하세요."
echo "✅ 다음 템플릿 중 하나를 선택하세요:"
echo ""
echo "   1. 🌟 학생 성장 상세 리포트 (추천)"
echo "   2. 🎓 모던 학원 소개"
echo "   3. 🚀 무료 체험 신청"
echo "   4. 🎉 이벤트 & 세미나"
echo "   5. 👥 학부모 커뮤니티"
echo ""
read -p "템플릿을 선택했으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 5: 학생 및 페이지 정보 입력"
echo "=================================================="
echo ""
echo "✅ 다음 정보를 입력하세요:"
echo ""
echo "   • 학생 선택: 아무 학생이나 선택"
echo "   • 제목: 템플릿 테스트 랜딩페이지"
echo "   • 부제목: 2024년 1학기 성과 리포트"
echo "   • 폴더: (선택사항)"
echo "   • 시작일: 2024-03-01"
echo "   • 종료일: 2024-08-31"
echo ""
read -p "정보를 입력했으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 6: Console 확인 (생성 전)"
echo "=================================================="
echo ""
echo -e "${YELLOW}⚠️  생성 버튼을 누르기 전에 Console을 확인하세요!${NC}"
echo ""
echo "✅ Console에 다음과 같은 로그가 있어야 합니다:"
echo ""
echo -e "${GREEN}   ✅ Selected template: [template ID]${NC}"
echo -e "${GREEN}   ✅ Template HTML length: [큰 숫자]${NC}"
echo ""
read -p "Console을 확인했으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 7: 랜딩페이지 생성"
echo "=================================================="
echo ""
echo "✅ '랜딩페이지 생성' 버튼을 클릭하세요."
echo ""
echo -e "${YELLOW}⚠️  생성 버튼을 클릭한 후:${NC}"
echo ""
echo "1. Console 탭에서 다음 로그를 확인하세요:"
echo ""
echo -e "${GREEN}   🔍 Sending to API: {${NC}"
echo -e "${GREEN}      hasTemplateHtml: true,${NC}"
echo -e "${GREEN}      templateHtmlLength: [큰 숫자]  // ⚠️ 0이 아니어야 함!${NC}"
echo -e "${GREEN}   }${NC}"
echo ""
echo "2. Network 탭으로 이동하세요."
echo ""
echo "3. 'landing-pages' 요청을 찾아 클릭하세요."
echo ""
echo "4. Payload 탭에서 'templateHtml' 필드를 확인하세요."
echo "   - 필드가 있어야 함"
echo "   - 값이 HTML 코드여야 함"
echo ""
echo "5. Response 탭에서 성공 응답을 확인하세요:"
echo ""
echo -e "${GREEN}   {${NC}"
echo -e "${GREEN}     \"success\": true,${NC}"
echo -e "${GREEN}     \"id\": \"lp_...\",${NC}"
echo -e "${GREEN}     \"url\": \"https://...\"${NC}"
echo -e "${GREEN}   }${NC}"
echo ""
read -p "랜딩페이지 생성이 완료되었으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 8: 생성된 랜딩페이지 확인"
echo "=================================================="
echo ""
echo "✅ 응답에서 받은 URL을 새 탭에서 열어보세요."
echo ""
echo -e "${YELLOW}확인할 사항:${NC}"
echo ""
echo "1. ✅ 선택한 템플릿의 디자인이 적용되었는가?"
echo "2. ✅ 제목이 올바르게 표시되는가?"
echo "3. ✅ 부제목이 올바르게 표시되는가?"
echo "4. ✅ 템플릿의 스타일(색상, 레이아웃)이 보이는가?"
echo "5. ✅ 변수가 치환되었는가? (예: {{title}}, {{subtitle}})"
echo ""
read -p "랜딩페이지를 확인했으면 Enter를 눌러주세요..."

echo ""
echo "=================================================="
echo "📋 Step 9: 결과 입력"
echo "=================================================="
echo ""
echo -e "${BLUE}템플릿이 올바르게 적용되었나요?${NC}"
echo ""
echo "1) ✅ 예 - 템플릿 디자인이 완벽하게 적용되었습니다."
echo "2) ❌ 아니오 - 기본 HTML만 보입니다."
echo "3) ⚠️  부분적으로 - 일부만 적용되었습니다."
echo ""
read -p "결과를 선택하세요 (1/2/3): " result

echo ""
case $result in
  1)
    echo -e "${GREEN}=================================================="
    echo "🎉 성공! 템플릿 시스템이 정상 작동합니다!"
    echo "==================================================${NC}"
    echo ""
    echo "✅ 모든 것이 올바르게 작동하고 있습니다."
    echo ""
    echo "다음 단계:"
    echo "1. 다른 템플릿으로도 테스트해보세요."
    echo "2. 실제 학생 데이터로 랜딩페이지를 생성해보세요."
    echo "3. 생성된 랜딩페이지를 학부모에게 공유해보세요."
    ;;
  2)
    echo -e "${YELLOW}=================================================="
    echo "⚠️  템플릿이 적용되지 않았습니다"
    echo "==================================================${NC}"
    echo ""
    echo "문제 해결 방법:"
    echo ""
    echo "1. Console에서 'hasTemplateHtml: true' 확인"
    echo "   - false라면: 템플릿 선택이 안 된 것입니다."
    echo ""
    echo "2. Console에서 'templateHtmlLength' 확인"
    echo "   - 0이라면: 템플릿에 HTML이 없는 것입니다."
    echo ""
    echo "3. Network에서 Payload 확인"
    echo "   - 'templateHtml' 필드가 없다면: 프론트엔드 오류입니다."
    echo ""
    echo "4. Cloudflare Dashboard 로그 확인"
    echo "   - '⚠️ Using default HTML' 로그가 보인다면:"
    echo "     백엔드가 templateHtml을 받지 못한 것입니다."
    echo ""
    echo "자세한 디버깅 방법은 TEMPLATE_VERIFICATION_COMPLETE.md를 참고하세요."
    ;;
  3)
    echo -e "${YELLOW}=================================================="
    echo "⚠️  템플릿이 부분적으로 적용되었습니다"
    echo "==================================================${NC}"
    echo ""
    echo "가능한 원인:"
    echo ""
    echo "1. 변수 치환 오류"
    echo "   - 일부 {{변수}}가 그대로 보이는가?"
    echo "   - 백엔드 변수 치환 로직을 확인하세요."
    echo ""
    echo "2. CSS 로딩 오류"
    echo "   - 스타일이 깨져 보이는가?"
    echo "   - Tailwind CDN 로딩을 확인하세요."
    echo ""
    echo "3. 템플릿 HTML 손상"
    echo "   - 템플릿 원본을 확인하세요."
    echo "   - /api/landing/templates에서 HTML 조회"
    echo ""
    echo "자세한 디버깅 방법은 TEMPLATE_VERIFICATION_COMPLETE.md를 참고하세요."
    ;;
  *)
    echo -e "${YELLOW}잘못된 입력입니다.${NC}"
    ;;
esac

echo ""
echo "=================================================="
echo "📚 추가 리소스"
echo "=================================================="
echo ""
echo "• 검증 문서: TEMPLATE_VERIFICATION_COMPLETE.md"
echo "• 수정 가이드: LANDING_PAGE_TEMPLATE_FIX.md"
echo "• 자동 테스트: ./test-landing-template.sh"
echo ""
echo "• Template API: /api/landing/templates"
echo "• Landing Page API: /api/admin/landing-pages"
echo ""
echo "• 프론트엔드 코드:"
echo "  - src/app/dashboard/admin/landing-pages/create/page.tsx"
echo ""
echo "• 백엔드 코드:"
echo "  - functions/api/admin/landing-pages.ts"
echo "  - functions/api/landing/templates.ts"
echo ""
echo "=================================================="
echo "테스트 완료!"
echo "=================================================="
