#!/bin/bash

# 요금제 승인 및 적용 전체 플로우 테스트
# Test the complete subscription approval and application flow

API_BASE="https://superplacestudy.pages.dev"

echo "========================================="
echo "요금제 승인 및 적용 테스트"
echo "========================================="
echo ""

# 1. 현재 요금제 목록 확인
echo "1️⃣ 현재 요금제 목록 확인"
echo "GET $API_BASE/api/admin/pricing-plans"
PLANS=$(curl -s "$API_BASE/api/admin/pricing-plans")
echo "$PLANS" | jq -r '.plans[] | "- \(.id): \(.name) (학생: \(.max_students), 숙제검사: \(.max_homework_checks), AI분석: \(.max_ai_analysis))"'
echo ""

# 스타터 플랜 ID 가져오기
PLAN_ID=$(echo "$PLANS" | jq -r '.plans[] | select(.name == "스타터") | .id')
echo "테스트에 사용할 플랜: $PLAN_ID"
echo ""

# 2. 요금제 신청 생성 (시뮬레이션)
echo "2️⃣ 요금제 신청 데이터 시뮬레이션"
TEST_REQUEST_ID="req-$(date +%s)-test"
TEST_USER_ID="user-test-$(date +%s)"
echo "신청 ID: $TEST_REQUEST_ID"
echo "사용자 ID: $TEST_USER_ID"
echo ""

# 3. 요금제 승인 API 테스트 준비
echo "3️⃣ 요금제 승인 시나리오"
echo ""
echo "📋 승인 시 예상 동작:"
echo "  - subscription_requests 테이블 상태 업데이트 (status='approved')"
echo "  - user_subscriptions 테이블에 구독 정보 INSERT/UPDATE"
echo "  - pricing_plans에서 한도 값 읽기:"
STARTER_PLAN=$(echo "$PLANS" | jq -r '.plans[] | select(.name == "스타터")')
echo "    • max_students: $(echo "$STARTER_PLAN" | jq -r '.max_students')"
echo "    • max_homework_checks: $(echo "$STARTER_PLAN" | jq -r '.max_homework_checks')"
echo "    • max_ai_analysis: $(echo "$STARTER_PLAN" | jq -r '.max_ai_analysis')"
echo "    • max_similar_problems: $(echo "$STARTER_PLAN" | jq -r '.max_similar_problems')"
echo "    • max_landing_pages: $(echo "$STARTER_PLAN" | jq -r '.max_landing_pages')"
echo ""
echo "  - user_subscriptions에 저장될 컬럼:"
echo "    • current_students = 0 (현재 사용량)"
echo "    • current_homework_checks = 0"
echo "    • current_ai_analysis = 0"
echo "    • current_similar_problems = 0"
echo "    • current_landing_pages = 0"
echo "    • max_students = 30"
echo "    • max_homework_checks = 720"
echo "    • max_ai_analysis = 50"
echo "    • max_similar_problems = 30"
echo "    • max_landing_pages = 40"
echo ""

# 4. 학생 추가 시 한도 체크
echo "4️⃣ 학생 추가 시 한도 체크 시나리오"
echo ""
echo "📋 체크 로직 (subscription/check-limit API):"
echo "  1. user_subscriptions에서 userId로 active 구독 조회"
echo "  2. 현재 사용량(current_students) vs 최대 한도(max_students) 비교"
echo "  3. max_students = -1 이면 무제한 허용"
echo "  4. current_students >= max_students 이면 LIMIT_EXCEEDED 오류"
echo "  5. 통과 시 current_students += 1 증가"
echo ""

# 5. 학원 상세 페이지에서 구독 정보 확인
echo "5️⃣ 학원 상세 페이지 구독 정보 표시"
echo ""
echo "📋 표시될 정보 (academies API):"
echo "  - planName: 요금제 이름 (예: '스타터')"
echo "  - status: 구독 상태 (active/expired)"
echo "  - maxStudents: 최대 학생 수 (30)"
echo "  - usedStudents: 현재 학생 수 (실제 User 테이블에서 STUDENT role 카운트)"
echo "  - maxHomeworkChecks: 숙제 검사 한도 (720)"
echo "  - usedHomeworkChecks: 사용한 숙제 검사 횟수 (0)"
echo "  - maxAIAnalysis: AI 분석 한도 (50)"
echo "  - usedAIAnalysis: 사용한 AI 분석 횟수 (0)"
echo "  - maxSimilarProblems: 유사문제 한도 (30)"
echo "  - usedSimilarProblems: 사용한 유사문제 횟수 (0)"
echo "  - maxLandingPages: 랜딩페이지 한도 (40)"
echo "  - usedLandingPages: 사용한 랜딩페이지 수 (0)"
echo "  - startDate, endDate: 구독 기간"
echo "  - daysRemaining: 남은 일수"
echo ""

# 6. 전체 플로우 요약
echo "========================================="
echo "✅ 수정 완료된 전체 플로우"
echo "========================================="
echo ""
echo "1️⃣ 요금제 승인 (POST /api/admin/subscription-approvals)"
echo "   • pricing_plans에서 max_students 등 한도 값 읽기"
echo "   • user_subscriptions에 INSERT/UPDATE"
echo "   • 컬럼명: current_students, max_students 등 (실제 DB 스키마 사용)"
echo ""
echo "2️⃣ 학생 추가 시 한도 체크 (POST /api/subscription/check-limit)"
echo "   • type='student', action='check' 또는 'increment'"
echo "   • current_students vs max_students 비교"
echo "   • max_students = -1 이면 무제한"
echo ""
echo "3️⃣ 학원 상세 페이지 (GET /api/admin/academies?id=xxx)"
echo "   • user_subscriptions 조회하여 구독 정보 표시"
echo "   • 모든 한도와 사용량 표시"
echo "   • 실제 학생/교사 수와 한도 비교 진행바 표시"
echo ""
echo "4️⃣ 모든 기능에 한도 적용"
echo "   • 학생 추가: current_students"
echo "   • 숙제 검사: current_homework_checks"
echo "   • AI 분석: current_ai_analysis"
echo "   • 유사문제: current_similar_problems"
echo "   • 랜딩페이지: current_landing_pages"
echo ""

echo "========================================="
echo "📊 DB 컬럼 매핑 정리"
echo "========================================="
echo ""
echo "pricing_plans 테이블:"
echo "  • max_students, max_homework_checks, max_ai_analysis,"
echo "  • max_similar_problems, max_landing_pages"
echo ""
echo "user_subscriptions 테이블:"
echo "  사용량: current_students, current_homework_checks, current_ai_analysis,"
echo "         current_similar_problems, current_landing_pages"
echo "  한도:   max_students, max_homework_checks, max_ai_analysis,"
echo "         max_similar_problems, max_landing_pages"
echo ""

echo "========================================="
echo "✅ 테스트 완료"
echo "========================================="
echo ""
echo "다음 단계:"
echo "1. 관리자 페이지에서 요금제 신청 승인 테스트"
echo "2. 승인된 학원에서 학생 추가 테스트"
echo "3. 학원 상세 페이지에서 구독 정보 확인"
echo "4. 한도 초과 시 오류 메시지 확인"
echo ""
