#!/bin/bash

echo "======================================"
echo "학원장 대시보드 데이터 검증"
echo "======================================"
echo ""

echo "⏰ 현재 시간: $(TZ='Asia/Seoul' date '+%Y-%m-%d %H:%M:%S KST')"
echo ""

echo "📦 최신 커밋 정보:"
git log -1 --oneline
echo ""

echo "======================================"
echo "1. 프론트엔드 대시보드 페이지 확인"
echo "======================================"

echo ""
echo "📄 src/app/dashboard/page.tsx - 학원장 섹션 (Line 405-607):"
sed -n '405,430p' src/app/dashboard/page.tsx | head -20

echo ""
echo "======================================"
echo "2. API 엔드포인트 응답 구조 확인"
echo "======================================"

echo ""
echo "📄 functions/api/dashboard/director-stats.ts - 응답 구조:"
grep -A 50 "return new Response" functions/api/dashboard/director-stats.ts | head -30

echo ""
echo "======================================"
echo "3. 데이터베이스 테이블 확인"
echo "======================================"

echo ""
echo "📊 필요한 테이블들:"
echo "  - users (학생/교사 정보)"
echo "  - attendance (출석 데이터)"
echo "  - homework_submissions (숙제 제출 데이터)"
echo "  - classes (수업 정보)"

echo ""
echo "======================================"
echo "✅ 테스트 방법"
echo "======================================"
echo ""
echo "1. 학원장 계정으로 로그인:"
echo "   https://superplacestudy.pages.dev/login"
echo ""
echo "2. 대시보드 접속:"
echo "   https://superplacestudy.pages.dev/dashboard"
echo ""
echo "3. 확인할 통계 카드:"
echo "   ✓ 전체 학생 수"
echo "   ✓ 오늘 출석"
echo "   ✓ 숙제 제출"
echo "   ✓ 숙제 미제출"
echo ""
echo "4. 확인할 리스트 섹션:"
echo "   ✓ 오늘 출석 알림 (최근 5명)"
echo "   ✓ 숙제 검사 결과 (최근 5개)"
echo "   ✓ 숙제 미제출 (최근 5명)"
echo ""
echo "5. 브라우저 콘솔 (F12) 로그 확인:"
echo "   - API 호출 URL"
echo "   - 응답 데이터 구조"
echo "   - 에러 메시지"
echo ""
echo "======================================"
echo "🔧 문제 해결"
echo "======================================"
echo ""
echo "데이터가 0으로 표시되는 경우:"
echo "  1. 출석 데이터 확인:"
echo "     - attendance 테이블에 오늘 날짜 데이터 있는지 확인"
echo "  2. 숙제 데이터 확인:"
echo "     - homework_submissions 테이블에 데이터 있는지 확인"
echo "  3. 학원 ID 확인:"
echo "     - localStorage의 user.academy_id 값 확인"
echo "     - 해당 학원에 속한 학생/교사가 있는지 확인"
echo ""
echo "======================================"

