#!/bin/bash

echo "════════════════════════════════════════════════════════════════════════"
echo "✅ 숙제 검사 카운트 수정 완료"
echo "════════════════════════════════════════════════════════════════════════"
echo ""
echo "📌 수정 내용:"
echo "   1. 숙제 검사 카운트 로직 변경"
echo "      - homework_submissions (제출 건수) → homework_images (업로드된 페이지 수)"
echo "      - 설정 페이지에 정확한 숫자 표시"
echo ""
echo "   2. 초과 시 완전 차단 로직 추가"
echo "      - 숙제 제출 시 현재 사용량 + 제출하려는 페이지 수 검증"
echo "      - maxHomeworkChecks 초과 시 403 Forbidden 반환"
echo "      - 에러 메시지: 현재 사용량, 한도, 시도한 페이지 수 포함"
echo ""
echo "📂 수정된 파일:"
echo "   - functions/api/subscription/check.ts (카운트 로직)"
echo "   - functions/api/homework/submit/index.ts (차단 로직)"
echo ""
echo "🚀 배포 정보:"
COMMIT=$(git log -1 --format="%h" 2>/dev/null || echo "unknown")
echo "   - Commit: $COMMIT"
echo "   - 배포 URL: https://superplacestudy.pages.dev"
echo "   - 설정 페이지: https://superplacestudy.pages.dev/dashboard/settings/"
echo ""
echo "⏳ Cloudflare Pages 배포 전파 중... (약 5분 소요)"
echo ""
echo "✅ 배포 후 확인사항:"
echo "   1. https://superplacestudy.pages.dev/dashboard/settings/ 접속"
echo "   2. '플랜' 섹션의 '숙제 검사' 숫자 확인"
echo "   3. 업로드된 페이지 수가 정확하게 표시되는지 확인"
echo "   4. 한도 초과 시 숙제 제출이 차단되는지 테스트"
echo ""
echo "🎯 예상 결과:"
echo "   - 설정 페이지: 업로드된 페이지 수 정확 표시"
echo "   - 한도 초과 시: 403 에러로 제출 차단"
echo "   - 다른 기능: 정상 동작 (영향 없음)"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
