name = "superplacestudy"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

# Cloudflare Pages Functions AI 바인딩
[env.production]
ai = { binding = "AI" }

[env.preview]
ai = { binding = "AI" }
