// Alimtalk Template Registration & Status Check API
// POST /api/kakao/templates/register - Solapi에 템플릿 등록 신청
// GET /api/kakao/templates/status?templateId=xxx - 승인 상태 조회

// CORS headers
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

// Handle OPTIONS
export async function onRequestOptions() {
  return new Response(null, { headers: corsHeaders });
}

// Create HMAC signature for Solapi (동일한 서명 방식 사용)
async function createSolapiSignature(apiSecret: string) {
  const date = new Date().toISOString();
  const salt = Math.random().toString(36).substring(2, 15);
  const message = date + salt;
  
  const encoder = new TextEncoder();
  const keyData = encoder.encode(apiSecret);
  const messageData = encoder.encode(message);
  
  const cryptoKey = await crypto.subtle.importKey(
    'raw',
    keyData,
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  
  const signature = await crypto.subtle.sign('HMAC', cryptoKey, messageData);
  
  // ArrayBuffer를 hex 문자열로 변환
  const signatureHex = Array.from(new Uint8Array(signature))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
  
  console.log('✅ 서명 생성 완료:', {
    signatureLength: signatureHex.length,
    signaturePreview: signatureHex.substring(0, 16) + '...',
  });

  return { date, salt, signature: signatureHex };
}

// POST: Solapi에 템플릿 등록 신청
export async function onRequestPost(context: any) {
  const { request, env } = context;

  try {
    const body = await request.json();
    const {
      userId,
      channelId,
      pfId,              // 프론트에서 받은 pfId (채널명 또는 실제 pfId)
      templateCode,      // 사용자가 정한 템플릿 코드 (비어있으면 자동 생성)
      templateName,      // 템플릿 이름
      content,           // 템플릿 내용
      categoryCode,      // 카테고리 코드 (예: 008, 012 등)
      messageType,       // BA (기본형), EX (부가정보형), AD (광고추가형), MI (복합형)
      emphasizeType,     // NONE, TEXT, IMAGE
      buttons,           // 버튼 배열
      extra,             // 부가정보 (강조 유형일 때)
      securityFlag,      // 보안 템플릿 여부
      variables,         // 변수 목록 (배열)
    } = body;

    console.log('📝 템플릿 등록 신청 (원본):', { userId, channelId, pfId, templateCode, templateName });

    if (!userId || !channelId || !templateName || !content) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Missing required fields: userId, channelId, templateName, content' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // 🔧 템플릿 코드 자동 생성 (비어있거나 없으면)
    const finalTemplateCode = templateCode && templateCode.trim() 
      ? templateCode 
      : `TPL_${Date.now()}_${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
    
    console.log('🔑 템플릿 코드:', {
      original: templateCode,
      generated: finalTemplateCode,
      isAutoGenerated: !templateCode || !templateCode.trim()
    });

    // 🔍 핵심: DB에서 실제 pfId 조회 (채널 이름 → 32자리 pfId로 변환)
    let academyPhone = null;
    let realPfId = null; // 실제 Solapi pfId
    
    try {
      // 1. 사용자 전화번호 조회
      const userResult = await env.DB.prepare(`
        SELECT phone, academy_name FROM users WHERE id = ?
      `).bind(userId).first();
      
      if (userResult && userResult.phone) {
        academyPhone = userResult.phone;
        console.log('📞 학원장 전화번호 조회 성공:', academyPhone);
      }
      
      // 2. 카카오 채널 정보 조회 (channelId로 실제 pfId 찾기)
      const channelResult = await env.DB.prepare(`
        SELECT id, channelName, solapiChannelId, phoneNumber FROM KakaoChannel 
        WHERE id = ?
      `).bind(channelId).first();
      
      console.log('🔎 DB 조회 결과:', {
        channelId,
        found: !!channelResult,
        channelName: channelResult?.channelName,
        solapiChannelId: channelResult?.solapiChannelId,
      });
      
      if (channelResult) {
        if (channelResult.solapiChannelId) {
          realPfId = channelResult.solapiChannelId;
          console.log('✅ 실제 pfId 조회 성공:', realPfId);
        } else {
          console.error('❌ solapiChannelId가 DB에 없습니다!');
          return new Response(
            JSON.stringify({ 
              success: false, 
              error: '카카오 채널의 pfId가 등록되지 않았습니다. 채널을 먼저 연동해주세요.',
              details: '관리자에게 문의하세요: solapiChannelId 누락'
            }),
            { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
          );
        }
        
        if (!academyPhone && channelResult.phoneNumber) {
          academyPhone = channelResult.phoneNumber;
          console.log('📞 채널 전화번호 조회 성공:', academyPhone);
        }
      } else {
        console.error('❌ 채널을 찾을 수 없습니다:', channelId);
        return new Response(
          JSON.stringify({ 
            success: false, 
            error: '선택한 카카오 채널을 찾을 수 없습니다.',
            details: `channelId: ${channelId}`
          }),
          { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
    } catch (dbError: any) {
      console.error('⚠️ 학원 정보 조회 실패:', dbError);
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'DB 조회 실패',
          details: dbError.message
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    console.log('🏫 최종 학원 정보:', { academyPhone, academyPfId });

    // Get Solapi credentials (여러 가능한 환경 변수명 시도)
    const envAny = env as any;
    const SOLAPI_API_KEY = (envAny['SOLAPI_API_Key '] || envAny['SOLAPI_API_Key'] || envAny.SOLAPI_API_Key || envAny.SOLAPI_API_KEY)?.trim();
    const SOLAPI_API_SECRET = (envAny.SOLAPI_API_SECRET || envAny.SOLAPI_API_Secret || envAny['SOLAPI_API_Secret'])?.trim();

    console.log('🔑 Solapi 자격 증명:', {
      keyExists: !!SOLAPI_API_KEY,
      secretExists: !!SOLAPI_API_SECRET,
      keyPreview: SOLAPI_API_KEY?.substring(0, 8) + '...',
    });

    if (!SOLAPI_API_KEY || !SOLAPI_API_SECRET) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Solapi credentials not configured',
          details: {
            keyExists: !!SOLAPI_API_KEY,
            secretExists: !!SOLAPI_API_SECRET,
          }
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Create HMAC signature
    const { date, salt, signature } = await createSolapiSignature(SOLAPI_API_SECRET);

    // Prepare template data for Solapi
    const templateData: any = {
      pfId: realPfId, // DB에서 조회한 실제 32자리 pfId
      templateId: finalTemplateCode,
      name: templateName,
      content: content,
      categoryCode: categoryCode || '008', // Default to 일반 카테고리
      messageType: messageType || 'BA',
      securityFlag: securityFlag || false
    };
    
    // ❌ senderKey 제거 - Solapi 템플릿 등록에는 필요없음
    // (알림톡 발송 시에만 사용)

    // Add buttons if provided
    if (buttons && Array.isArray(buttons) && buttons.length > 0) {
      templateData.buttons = buttons.map((btn: any) => ({
        ordering: btn.ordering || 1,
        type: btn.type || 'WL', // WL (웹링크), AL (앱링크), BK (봇키워드), MD (메시지전달)
        name: btn.name,
        linkMo: btn.linkMo || btn.url,
        linkPc: btn.linkPc || btn.url,
        linkIos: btn.linkIos,
        linkAnd: btn.linkAnd
      }));
    }

    // Add emphasize type and extra if provided
    if (emphasizeType && emphasizeType !== 'NONE') {
      templateData.emphasizeType = emphasizeType;
      // ✅ extra는 JSON 문자열로 변환
      if (extra && typeof extra === 'object') {
        templateData.extra = JSON.stringify(extra);
      } else if (extra && typeof extra === 'string') {
        templateData.extra = extra;
      }
    }

    console.log('🚀 Solapi API 호출:', templateData);
    console.log('🔐 인증 헤더:', {
      apiKeyPreview: SOLAPI_API_KEY?.substring(0, 8) + '...',
      date,
      salt,
      signaturePreview: signature.substring(0, 16) + '...',
    });

    // Call Solapi API to register template
    const solapiResponse = await fetch('https://api.solapi.com/kakao/v1/templates', {
      method: 'POST',
      headers: {
        'Authorization': `HMAC-SHA256 apiKey=${SOLAPI_API_KEY}, date=${date}, salt=${salt}, signature=${signature}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(templateData)
    });

    const solapiData = await solapiResponse.json();

    console.log('📥 Solapi 응답:', {
      status: solapiResponse.status,
      ok: solapiResponse.ok,
      data: solapiData
    });

    if (!solapiResponse.ok) {
      // Solapi API 에러 - 상세 정보 반환
      const errorMessages = [];
      
      if (solapiData.errorMessage) {
        errorMessages.push(solapiData.errorMessage);
      }
      
      if (solapiData.message) {
        errorMessages.push(solapiData.message);
      }
      
      // 검증 오류 메시지 파싱
      if (Array.isArray(solapiData.errors)) {
        errorMessages.push(...solapiData.errors);
      }
      
      console.error('❌ Solapi 템플릿 등록 실패:', {
        errorCode: solapiData.errorCode,
        errorMessages,
        fullResponse: solapiData
      });
      
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: errorMessages.join(', ') || 'Solapi template registration failed',
          details: solapiData,
          code: solapiData.errorCode,
          validation: {
            pfId: realPfId,
            pfIdLength: academyPfId?.length,
            templateId: finalTemplateCode,
            hasExtra: !!templateData.extra,
            extraType: typeof templateData.extra,
          }
        }),
        { status: solapiResponse.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Save to local database
    const id = `tpl_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    const now = new Date().toISOString();

    await env.DB.prepare(`
      INSERT INTO AlimtalkTemplate (
        id, userId, channelId, templateCode, templateName, content,
        categoryCode, messageType, emphasizeType, buttons, quickReplies, variables,
        solapiTemplateId, status, inspectionStatus, senderPhone, senderPfId, createdAt, updatedAt
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).bind(
      id,
      userId,
      channelId,
      finalTemplateCode, // 자동 생성된 코드 저장
      templateName,
      content,
      categoryCode || '008',
      messageType || 'BA',
      emphasizeType || 'NONE',
      buttons ? JSON.stringify(buttons) : null,
      null,
      variables ? JSON.stringify(variables) : null,
      finalTemplateCode, // solapiTemplateId
      'ACTIVE',
      solapiData.status || 'PENDING', // Solapi 응답의 상태 저장
      academyPhone, // 학원 전화번호 저장
      realPfId,  // 실제 Solapi pfId 저장
      now,
      now
    ).run();

    return new Response(
      JSON.stringify({ 
        success: true, 
        template: {
          id,
          templateCode: finalTemplateCode, // 자동 생성된 코드 반환
          templateName,
          status: solapiData.status,
          inspectionStatus: solapiData.inspectionStatus
        },
        solapi: solapiData,
        message: '템플릿이 Solapi에 등록 신청되었습니다. 카카오 승인 대기 중입니다.'
      }),
      { status: 201, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('❌ 템플릿 등록 오류:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: 'Internal server error',
        details: error.message 
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
}

// GET: 템플릿 승인 상태 조회
export async function onRequestGet(context: any) {
  const { request, env } = context;
  const url = new URL(request.url);

  try {
    const templateId = url.searchParams.get('templateId'); // 템플릿 코드
    const pfId = url.searchParams.get('pfId');             // 카카오 채널 PF ID
    const userId = url.searchParams.get('userId');

    if (!templateId || !pfId) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'templateId and pfId are required' 
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('🔍 템플릿 상태 조회:', { templateId, pfId });

    // Get Solapi credentials (여러 가능한 환경 변수명 시도)
    const envAny = env as any;
    const SOLAPI_API_KEY = (envAny['SOLAPI_API_Key '] || envAny['SOLAPI_API_Key'] || envAny.SOLAPI_API_Key || envAny.SOLAPI_API_KEY)?.trim();
    const SOLAPI_API_SECRET = (envAny.SOLAPI_API_SECRET || envAny.SOLAPI_API_Secret || envAny['SOLAPI_API_Secret'])?.trim();

    console.log('🔑 Solapi 자격 증명:', {
      keyExists: !!SOLAPI_API_KEY,
      secretExists: !!SOLAPI_API_SECRET,
      keyPreview: SOLAPI_API_KEY?.substring(0, 8) + '...',
    });

    if (!SOLAPI_API_KEY || !SOLAPI_API_SECRET) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: 'Solapi credentials not configured',
          details: {
            keyExists: !!SOLAPI_API_KEY,
            secretExists: !!SOLAPI_API_SECRET,
          }
        }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Create HMAC signature
    const { date, salt, signature } = await createSolapiSignature(SOLAPI_API_SECRET);

    console.log('🔍 템플릿 상태 조회 요청:', {
      templateId,
      pfId,
      apiKeyPreview: SOLAPI_API_KEY?.substring(0, 8) + '...',
      date,
      salt,
      signaturePreview: signature.substring(0, 16) + '...',
    });

    // Call Solapi API to get template status
    const solapiResponse = await fetch(
      `https://api.solapi.com/kakao/v1/templates/${pfId}/${templateId}`,
      {
        method: 'GET',
        headers: {
          'Authorization': `HMAC-SHA256 apiKey=${SOLAPI_API_KEY}, date=${date}, salt=${salt}, signature=${signature}`,
        }
      }
    );

    const solapiData = await solapiResponse.json();

    console.log('📥 Solapi 템플릿 상태:', solapiData);

    if (!solapiResponse.ok) {
      return new Response(
        JSON.stringify({ 
          success: false, 
          error: solapiData.errorMessage || 'Failed to get template status',
          details: solapiData
        }),
        { status: solapiResponse.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Update local database with latest status
    if (userId) {
      try {
        await env.DB.prepare(`
          UPDATE AlimtalkTemplate
          SET inspectionStatus = ?, updatedAt = ?
          WHERE userId = ? AND templateCode = ?
        `).bind(
          solapiData.inspectionStatus || solapiData.status,
          new Date().toISOString(),
          userId,
          templateId
        ).run();
      } catch (dbError) {
        console.error('⚠️ DB 업데이트 실패:', dbError);
        // Continue anyway - DB update is not critical
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        template: solapiData,
        inspectionStatus: solapiData.inspectionStatus,
        status: solapiData.status,
        isApproved: solapiData.inspectionStatus === 'APR', // APR = 승인됨
        statusMessage: getStatusMessage(solapiData.inspectionStatus)
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('❌ 템플릿 상태 조회 오류:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: 'Internal server error',
        details: error.message 
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
}

// 승인 상태 메시지
function getStatusMessage(status: string): string {
  const statusMap: { [key: string]: string } = {
    'REQ': '등록 대기',
    'REG': '검수 대기',
    'APR': '승인됨 ✅',
    'REJ': '반려됨 ❌',
    'REV': '재검수 요청',
    'PENDING': '검수 대기',
  };
  return statusMap[status] || status;
}
